// ============================================================
// 质检数据文件 - 每次质检后由AI自动更新此文件
// 最后更新：2026-04-16
// ============================================================

const QC_CONFIG = {
  shopName: "客服质检系统",
  platform: "飞鸽客服系统",
  passScore: 85,
  lastUpdated: "2026-04-16",
  inspector: "AI质检系统",
};

const QC_SESSIONS = [
  {
    shop: "麦当劳官方旗舰店",
    id: "7629287021789463843",
    date: "2026-04-16",
    agent: "麦小妖",
    username: "Hero.",
    scenario: "订单配送问题咨询",
    duration: "中",
    evaluation: "正常",
    score: 88,
    deductions: [
      { item: "结束语缺失", points: -3, dim: 1 },
      { item: "未主动引导好评", points: -5, dim: 3 },
      { item: "配送异常未主动升级处理", points: -4, dim: 4 },
    ],
    improvedScript: "【结束语】感谢您联系麦当劳官方客服～本次问题已为您处理完毕，如有其他需要随时联系我们！祝您用餐愉快🍔\n【引导好评】如果我的服务让您满意，欢迎给我们一个好评，您的支持是我们进步的动力！",
    direction: "1.熟记标准结束语 2.配送异常主动询问赔偿/重送方案 3.结束前引导好评",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629288357469734184",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "连告别都双手插兜的女人",
    scenario: "优惠券使用咨询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待话术】稍等一下哦，我马上帮您查询～🔍 感谢您的耐心等待！",
    direction: "等待话术自然化，加入表情符号增加温度感",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629286288331408666",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "oO美少女社士Oo",
    scenario: "退款/退单处理",
    duration: "中",
    evaluation: "正常",
    score: 93,
    deductions: [
      { item: "未告知退款到账时效", points: -5, dim: 2 },
      { item: "结束语缺失", points: -2, dim: 1 },
    ],
    improvedScript: "【退款时效】退款已为您申请成功，预计1-3个工作日内退回至您的支付账户，请注意查收～如有疑问随时联系我们！",
    direction: "退款场景必须主动告知到账时效，减少用户二次咨询",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629283935947687168",
    date: "2026-04-16",
    agent: "麦小妖",
    username: "Chao·琛",
    scenario: "订单餐品问题投诉",
    duration: "中",
    evaluation: "正常",
    score: 90,
    deductions: [
      { item: "情绪安抚不足", points: -5, dim: 3 },
      { item: "解决方案告知不完整", points: -5, dim: 2 },
    ],
    improvedScript: "【安抚】非常抱歉给您带来了不好的用餐体验！🙏 我理解您的心情，我们会认真对待您的反馈，马上为您处理！\n【方案】您可以选择：①申请退款 ②重新配送 ③优惠补偿，请问您希望我们如何为您处理？",
    direction: "投诉场景优先安抚情绪，再提供多个解决方案供用户选择",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "missing-001",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "用户谢*",
    scenario: "会员权益咨询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】稍等哦～我帮您查一下会员权益详情，马上回来！🌟",
    direction: "等待话术自然化，体现品牌温度",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629284590573585727",
    date: "2026-04-16",
    agent: "麦小妖",
    username: "用户6786304109876",
    scenario: "配送进度查询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】请稍等一下哦，我马上为您查询配送进度～🛵",
    direction: "查询类问题等待话术加入预期时间，降低用户焦虑",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629281489502356787",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "🍾酥酥",
    scenario: "复杂退款+餐品投诉",
    duration: "长",
    evaluation: "正常",
    score: 77,
    deductions: [
      { item: "情绪安抚严重不足", points: -10, dim: 3 },
      { item: "未提供完整解决方案", points: -8, dim: 2 },
      { item: "结束语缺失", points: -5, dim: 1 },
    ],
    improvedScript: "【安抚】非常非常抱歉给您造成了这么大的困扰！😔 您的感受我完全理解，这确实是我们的失误，我一定全力为您解决！\n【完整方案】我现在为您申请退款+补偿券，退款预计1-3工作日到账，补偿券将直接发放至您账户，您看这样处理可以吗？",
    direction: "高情绪投诉：先道歉→共情→承担责任→完整方案→确认满意→标准结束语",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629282188898485545",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "Dazzy",
    scenario: "活动优惠咨询",
    duration: "短",
    evaluation: "正常",
    score: 95,
    deductions: [
      { item: "活动信息告知不完整", points: -5, dim: 2 },
    ],
    improvedScript: "【活动告知】活动使用条件：①满XX元可用 ②有效期至XX ③每账号限用X次 ④不可与其他优惠叠加，请您留意哦～",
    direction: "活动信息需完整告知：内容、使用门槛、有效期、限制条件",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629280632891278630",
    date: "2026-04-16",
    agent: "麦小妖",
    username: "蛋黄酥睡不醒",
    scenario: "配送时间咨询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】马上为您查询配送时间～请稍等片刻！🏃‍♀️",
    direction: "配送查询类统一使用活泼话术，体现效率感",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629274576890889507",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "给我买碗麻辣烫",
    scenario: "订单修改咨询",
    duration: "中",
    evaluation: "正常",
    score: 89,
    deductions: [
      { item: "未告知订单修改限制条件", points: -6, dim: 2 },
      { item: "结束语缺失", points: -5, dim: 1 },
    ],
    improvedScript: "【修改话术】关于订单修改，在商家开始制作前可以为您取消重下！如果已开始制作则无法修改，您的订单目前[状态]，[可以/无法]为您操作，请问需要我帮您处理吗？",
    direction: "修改类咨询需主动告知当前订单状态+修改规则，给出明确可操作方案",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629271914195748146",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "老虎猪咪",
    scenario: "餐品口味/质量反馈",
    duration: "中",
    evaluation: "正常",
    score: 92,
    deductions: [
      { item: "未主动提出补偿方案", points: -5, dim: 3 },
      { item: "信息记录不完整", points: -3, dim: 4 },
    ],
    improvedScript: "【主动补偿】非常感谢您的反馈！😊 我已将您的意见记录并反馈给门店。作为补偿，我为您申请一张[X元]优惠券，希望您下次能有更好的体验！",
    direction: "质量反馈场景：记录反馈+主动补偿+感谢用户，提升满意度",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629272930064565558",
    date: "2026-04-16",
    agent: "麦小东",
    username: "泡沫",
    scenario: "一般咨询",
    duration: "短",
    evaluation: "正常",
    score: 99,
    deductions: [
      { item: "措辞可更温暖", points: -1, dim: 1 },
    ],
    improvedScript: "【日常话术】"好的呢～" "没问题哦！" "您稍等哈～"",
    direction: "日常用语加入语气词和表情，提升对话温度",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629268726461826338",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "叫我一声贝塔",
    scenario: "发票开具咨询",
    duration: "中",
    evaluation: "正常",
    score: 90,
    deductions: [
      { item: "发票流程告知不完整", points: -5, dim: 2 },
      { item: "等待话术生硬", points: -5, dim: 1 },
    ],
    improvedScript: "【发票话术】发票申请：①订单完成后7天内 ②进入订单详情→申请发票 ③填写抬头和税号 ④电子发票24小时内发至邮箱。请问您需要普通发票还是增值税专用发票呢？",
    direction: "发票咨询需告知：申请入口、时间限制、发票类型、到达方式",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629267141044241674",
    date: "2026-04-16",
    agent: "麦小东",
    username: "禅茶一魏",
    scenario: "积分兑换咨询",
    duration: "中",
    evaluation: "正常",
    score: 94,
    deductions: [
      { item: "积分规则告知不完整", points: -6, dim: 2 },
    ],
    improvedScript: "【积分话术】积分说明：①当前积分[X]分 ②可兑换[商品名] ③积分有效期至[日期] ④每次兑换上限[X]分，请问您需要兑换哪款商品呢？",
    direction: "积分咨询一次性告知余额、可兑换内容、有效期、限制",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629269428043072768",
    date: "2026-04-16",
    agent: "麦小东",
    username: "好好睡觉",
    scenario: "配送问题处理",
    duration: "中",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】我马上为您处理配送问题，请稍等～🛵",
    direction: "配送问题紧迫感强，话术体现高效处理的态度",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629268998189761832",
    date: "2026-04-16",
    agent: "麦小薇",
    username: "梧桐树下的猫ao～",
    scenario: "套餐内容咨询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】我来为您介绍一下这款套餐～请稍等哦！🍟",
    direction: "产品介绍类话术体现专业性和热情",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629264483705259307",
    date: "2026-04-16",
    agent: "麦小东",
    username: "牛小迷",
    scenario: "优惠活动咨询",
    duration: "短",
    evaluation: "正常",
    score: 95,
    deductions: [
      { item: "优惠叠加规则未告知", points: -5, dim: 2 },
    ],
    improvedScript: "【优惠叠加】这个优惠券[可以/不可以]与其他活动叠加使用，使用时请注意哦～如您有多张优惠券，建议优先使用[XX]，这样更划算！",
    direction: "优惠咨询必须说明叠加规则，避免用户结算时发现不符预期",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629265502409442575",
    date: "2026-04-16",
    agent: "麦小东",
    username: "一路向前💃🏻",
    scenario: "订单超时投诉",
    duration: "中",
    evaluation: "正常",
    score: 93,
    deductions: [
      { item: "超时原因未解释", points: -5, dim: 2 },
      { item: "赔偿方案告知顺序不当", points: -2, dim: 3 },
    ],
    improvedScript: "【超时处理】非常抱歉您的订单配送超时了！😔 超时原因是[原因]。作为补偿，我为您申请[X元]优惠券/退还配送费，请问您希望哪种补偿方式呢？",
    direction: "超时投诉：道歉→解释原因→给补偿方案→让用户选择，体现透明度",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629261772624594217",
    date: "2026-04-16",
    agent: "麦小东",
    username: "VC",
    scenario: "新品推荐咨询",
    duration: "短",
    evaluation: "正常",
    score: 98,
    deductions: [
      { item: "未主动推荐关联产品", points: -2, dim: 3 },
    ],
    improvedScript: "【关联推荐】这款新品非常受欢迎！🌟 搭配[XX]一起点效果更好，目前还有[活动名]优惠，感兴趣可以了解一下哦～",
    direction: "新品咨询是推荐关联产品的好时机，可提升客单价",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629261942837871918",
    date: "2026-04-16",
    agent: "麦小东",
    username: "粧黎",
    scenario: "账户问题处理",
    duration: "短",
    evaluation: "正常",
    score: 98,
    deductions: [
      { item: "安全提示不足", points: -2, dim: 4 },
    ],
    improvedScript: "【安全提示】问题已为您处理好了～ 温馨提示：请注意保护您的账户信息安全，不要将密码等信息透露给他人哦！如有异常请及时联系我们！🔒",
    direction: "账户类操作结束后加入安全提示，体现品牌对信息安全的重视",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629228230427395334",
    date: "2026-04-16",
    agent: "麦小风",
    username: "抡大锤的阳哥",
    scenario: "配送路线咨询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】我帮您查询一下配送路线信息，请稍等～",
    direction: "查询类统一规范等待话术",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629225578717005056",
    date: "2026-04-16",
    agent: "麦小东",
    username: "✨",
    scenario: "退款进度查询",
    duration: "短",
    evaluation: "正常",
    score: 95,
    deductions: [
      { item: "退款进度说明不详细", points: -5, dim: 2 },
    ],
    improvedScript: "【退款进度】您的退款目前[状态]，预计[X]个工作日内退回至[支付方式]，如超时未到账请联系我们，我们会为您跟进处理！",
    direction: "退款进度查询必须给出明确预期时间，让用户心里有数",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629222498105673003",
    date: "2026-04-16",
    agent: "麦小淼",
    username: "Kali",
    scenario: "优惠券无法使用投诉",
    duration: "中",
    evaluation: "正常",
    score: 89,
    deductions: [
      { item: "未核实优惠券失效原因", points: -6, dim: 2 },
      { item: "解决方案单一", points: -5, dim: 3 },
    ],
    improvedScript: "【优惠券问题】我帮您查询一下这张优惠券的状态～[查询后] 这张券目前[状态/原因]，如果是系统问题我可以为您补发，您看可以吗？",
    direction: "优惠券问题先查原因再给方案，不要武断判断，体现专业性",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629219856222586121",
    date: "2026-04-16",
    agent: "麦小风",
    username: "天骄",
    scenario: "门店营业时间咨询",
    duration: "短",
    evaluation: "正常",
    score: 97,
    deductions: [
      { item: "等待话术略显生硬", points: -3, dim: 1 },
    ],
    improvedScript: "【等待】我来帮您查询门店营业时间，请稍等～🏪",
    direction: "门店信息查询类加入门店相关表情，增加亲和力",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629217275291157760",
    date: "2026-04-16",
    agent: "麦小淼",
    username: "小咪",
    scenario: "餐品少送投诉",
    duration: "中",
    evaluation: "正常",
    score: 93,
    deductions: [
      { item: "核实流程缺少步骤", points: -5, dim: 4 },
      { item: "未主动表达歉意", points: -2, dim: 3 },
    ],
    improvedScript: "【少送处理】非常抱歉！您反映少送了[餐品]，非常抱歉给您造成了不便！😔 我马上为您核实，[核实后] 确认少送了[餐品]，我现在为您安排补送/退款，请问您更希望哪种方式？",
    direction: "少送场景：先道歉→核实→确认→给方案，流程规范且有温度",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629215502698628392",
    date: "2026-04-16",
    agent: "麦小风",
    username: "下雨小鱼",
    scenario: "配送费用咨询",
    duration: "短",
    evaluation: "正常",
    score: 94,
    deductions: [
      { item: "配送费规则说明不完整", points: -6, dim: 2 },
    ],
    improvedScript: "【配送费说明】配送费根据距离计算，一般为[X-X]元；订单满[X]元免配送费；雨天/高峰期可能有附加费；会员享受[X]次/月免配送费权益，请问还有其他问题吗？",
    direction: "配送费咨询一次性说明计算规则、免费条件、特殊情况",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629214452944078116",
    date: "2026-04-16",
    agent: "麦小淼",
    username: "有你真好",
    scenario: "订单取消咨询",
    duration: "短",
    evaluation: "正常",
    score: 93,
    deductions: [
      { item: "取消后退款说明不完整", points: -5, dim: 2 },
      { item: "等待话术生硬", points: -2, dim: 1 },
    ],
    improvedScript: "【取消+退款】订单已为您取消成功！退款将在1-3个工作日内退回至您的[支付方式]，请注意查收。如有疑问欢迎随时联系我们！😊",
    direction: "取消订单必须配套说明退款时效，形成完整服务闭环",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629214104527619368",
    date: "2026-04-16",
    agent: "麦小风",
    username: "爱初见",
    scenario: "新用户首单咨询",
    duration: "短",
    evaluation: "正常",
    score: 96,
    deductions: [
      { item: "首单活动说明略显简略", points: -4, dim: 2 },
    ],
    improvedScript: "【首单引导】欢迎您首次光临麦当劳官方旗舰店！🎉 首单专属优惠：①下单时选择[优惠活动] ②满[X]元减[X]元 ③仅限首单使用 ④有效期至[日期]，希望您有愉快的用餐体验！",
    direction: "新用户场景重点做好首单引导，提升转化和后续复购率",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629207870537614633",
    date: "2026-04-16",
    agent: "麦小淼",
    username: "思念与海同眠",
    scenario: "外卖异常处理",
    duration: "中",
    evaluation: "正常",
    score: 93,
    deductions: [
      { item: "情绪安抚略显不足", points: -4, dim: 3 },
      { item: "处理方案未给选择", points: -3, dim: 3 },
    ],
    improvedScript: "【异常处理】非常抱歉您的外卖出现了问题！这让您等了这么久，真的很抱歉！😔 我为您提供两个解决方案：①[方案A] ②[方案B]，您希望我为您选择哪种方式呢？",
    direction: "异常处理给用户选择权；安抚话术需体现真诚歉意",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629204539727447311",
    date: "2026-04-16",
    agent: "麦小淼",
    username: "过客^O^",
    scenario: "积分到账查询",
    duration: "短",
    evaluation: "正常",
    score: 92,
    deductions: [
      { item: "积分到账时效未告知", points: -5, dim: 2 },
      { item: "结束语不完整", points: -3, dim: 1 },
    ],
    improvedScript: "【积分到账】积分一般在订单完成后[X]小时内到账，如超时未到账可能是[原因]，我帮您核实！[核实后] 已为您处理，积分将在[X]小时内到账，请注意查收！",
    direction: "积分到账查询需告知正常时效、超时原因及处理结果",
  },
  {
    shop: "麦当劳官方旗舰店",
    id: "7629251639857153280",
    date: "2026-04-16",
    agent: "麦小东",
    username: "刀刀枪枪",
    scenario: "返券规则咨询",
    duration: "中",
    evaluation: "差评-非常不满意",
    score: 81,
    deductions: [
      { item: "答非所问（返券≠退款）", points: -10, dim: 3 },
      { item: "情绪安抚不足", points: -5, dim: 3 },
      { item: "未主动澄清确认", points: -4, dim: 3 },
    ],
    improvedScript: "【返券话术】您好！关于返券活动：购买指定套餐后，系统会在订单完成后[X]小时内自动将优惠券返还至您的账户，您可在[APP/小程序]→我的→优惠券中查看。返券有效期为[X]天，请及时使用哦！\n\n【确认话术】我理解您是想问返券规则，对吗？（接收问题时先复述确认，再进行回答）",
    direction: "⚠️重点：1.区分返券/退款两个不同概念 2.接收问题先复述确认 3.答非所问时立即纠正并道歉",
  },
];

// 客服绩效汇总
const AGENT_SUMMARY = [
  { name: "麦小妖", count: 6, avg: 93.2, max: 97, min: 88, level: "良好", weeklyQuota: 3 },
  { name: "麦小薇", count: 10, avg: 90.7, max: 97, min: 77, level: "需改进", weeklyQuota: 5 },
  { name: "麦小东", count: 9, avg: 93.3, max: 99, min: 81, level: "良好", weeklyQuota: 5 },
  { name: "麦小风", count: 4, avg: 96.0, max: 97, min: 94, level: "优秀", weeklyQuota: 2 },
  { name: "麦小淼", count: 5, avg: 92.0, max: 93, min: 89, level: "良好", weeklyQuota: 3 },
];

// 质检标准
const QC_STANDARDS = [
  { dim: 1, name: "沟通体验与规范", desc: "开场白/结束语规范、等待话术、用语规范", deductRange: "扣1-5分/项", color: "#4CAF50" },
  { dim: 2, name: "业务知识与准确性", desc: "信息准确、方案完整告知", deductRange: "扣5-10分/项", color: "#2196F3" },
  { dim: 3, name: "沟通与解决问题能力", desc: "无重复询问、答非所问、情绪安抚", deductRange: "扣5-10分/项", color: "#FF9800" },
  { dim: 4, name: "流程与系统操作", desc: "建单准确、信息记录、必要时升级", deductRange: "扣5分/项", color: "#9C27B0" },
  { dim: 5, name: "严重错误（一票否决）", desc: "争吵、泄露隐私、私自承诺", deductRange: "直接0分", color: "#F44336" },
];
